### ISSUE TITLE
Production build doesn't work in a subdir

### ISSUE THREAD

**Issue by J05HI** [JunkyDeLuxe/angular4-starter#1]
Hello,

first thank you for the great work!
But I have a little problem deploying it in a subdir on my server. It can't find the assets and redirects to the home dir.

I hope you understand and can help me :)

**Comment by JunkyDeLuxe** [comment]
Hey,
 
Can you describe a bit more your problem ? which assets, mine or yours ?

I think the problem comes from webpackconfig.js with public path variable but not sure about that

**Comment by J05HI** [comment]
@JunkyDeLuxe 

Thanks for the fast answer!

I haven't changed anything yet, only running "npm run build" and then access it over my local xampp server.
This gives me the following 404s and the app stucks at the loading screen:
![capture](https://cloud.githubusercontent.com/assets/16399787/25316356/ff7306d8-2865-11e7-9689-72814f24c458.PNG)

Hopefully you can help me.

**Comment by JunkyDeLuxe** [comment]
You don't need xampp server to use this starter.
I will check tomorrow using xampp. I can see xampp finds correctly the index.html file. That's a good point.

I see your are using Windows, perhaps there is a problem with path files resolving
Indeed, '/' on linux equals '\' on windows.

I am not a Windows user so that will be tough for me to resolve your issue :s

**Comment by J05HI** [comment]
Okay thx!
I need a server for production, I can't run the node server on my web hosting then. 
But I think it has nothing to do with the operating system. You need to run the app in a separate path like I did.

**Comment by J05HI** [comment]
@JunkyDeLuxe
Any news? :)

**Comment by JunkyDeLuxe** [comment]
You have to change the index.html in the /dist. If you check it, you will see **all the files are included with absolute paths.**
ex: '/js/vendor.b0b06a7a53d2c02dfd70.js'

that's the problem.

You can also try modify the output variable in the webpackconfig in order to generate the good paths for your application.

The code now:
config.output = isTest ? {} : {
		path: root('dist'),
		publicPath: isProd ? '/' : 'http://localhost:8080/',
		filename: isProd ? 'js/[name].[hash].js' : 'js/[name].js',
		chunkFilename: isProd ? '[id].[hash].chunk.js' : '[id].chunk.js'
	};

You can try change the path like:

path: root('your_path...../dist'),

**Comment by J05HI** [comment]
@JunkyDeLuxe 
Thank you very much!!!
It's working now but if I refresh the site it get a 404 :(

**Comment by J05HI** [comment]
@JunkyDeLuxe 
Can you please fix the 404 on reload

**Comment by JunkyDeLuxe** [comment]
Hello,

I can't. The problem comes from your apache web server.
If you decide to go to /login and after that you refresh, your apache server will check if there is a /login url page before angular is loaded. obviously there is not a login url page ...

The only way to fix it is to tell to your apache web server to send a http response 200 when there is an url request.

**Comment by J05HI** [comment]
@JunkyDeLuxe 
And there is no other way?

**Comment by JunkyDeLuxe** [comment]
You have to rewrite your apache file configuration.
Each url request have to be redirected to the index.html file where angular is loaded.

**Comment by J05HI** [comment]
@JunkyDeLuxe 
That's not possible on a shared hoster
